//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int id { get; set; }
        public int subject { get; set; }
        public int weekDay { get; set; }
        public System.TimeSpan time { get; set; }
        public int duration { get; set; }
        public int teacher { get; set; }
        public string type { get; set; }
        public int classroom { get; set; }
        public int studentGroup { get; set; }
    
        public virtual Classroom Classroom1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual StudentGroup StudentGroup1 { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
