//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSubject
    {
        public int id { get; set; }
        public int student { get; set; }
        public int subject { get; set; }
        public string grade { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
